name: build an 18F.org eleventy site from repo

on:
  workflow_call:
    inputs:
      repo:
        description: Repo to build from
        required: true
        type: string
      base-url:
        description: The BASEURL to use for the site being built
        required: false
        default: ""
        type: string
      branch:
        description: The branch to checkout for building
        required: false
        default: main
        type: string
    secrets:
      token:
        description: Access token with read access to the 18F.org repo
        required: true
    outputs:
      path:
        description: Cache path for this built repo
        value: ${{ jobs.build.outputs.path }}
      key:
        description: Cache key for build output
        value: ${{ jobs.build.outputs.path }}

jobs:
  build:
    name: building a site
    runs-on: ubuntu-latest

    outputs:
      path: ${{ steps.slug.outputs.slug }}
      key: ${{ steps.key.outputs.key }}

    steps:
      - name: slugify repo
        id: slug
        run: |
          echo "slug=$(echo '${{ inputs.repo }}' | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)" >> $GITHUB_OUTPUT
      
      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.token }}

      - name: compute cache key
        id: key
        run: |
          echo "key=$(echo '${{ steps.slug.outputs.slug }}-${{ steps.checkout.outputs.commit}}')" >> $GITHUB_OUTPUT
  
      - uses: actions/cache@v4
        id: sha-cache
        with:
          key: ${{ steps.key.outputs.key }}
          path: ${{ steps.slug.outputs.slug }}

      - uses: actions/setup-node@v3
        if: steps.sha-cache.outputs.cache-hit != 'true'
        with:
          node-version: 22

      - name: build the site
        if: steps.sha-cache.outputs.cache-hit != 'true'
        env:
          BASEURL: ${{ inputs.base-url }}
          # ELEVENTY_ENV: production
        run: |
          npm ci
          npm run build

      - name: move to slug
        if: steps.sha-cache.outputs.cache-hit != 'true'
        run: mv _site ${{ steps.slug.outputs.slug }}
