name: deploy 18f.org

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    uses: team18f/site/.github/workflows/deploy.yaml
    secrets:
      token: ${{ secrets.CLONE_PAT }}
