name: deploy site

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/build-artifacts.yaml
    secrets:
      CLONE_PAT: ${{ secrets.CLONE_PAT }}

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: fetch artifacts
        uses: actions/download-artifact@v4
        with:
          name: _site

      - name: upload artifacts to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: deploy Pages
        uses: actions/deploy-pages@v4
