on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  deploy:
    name: deploy an 18f.org site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: build site
        run: |
          npm ci
          npm run build
  
      - name: upload artifacts to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
  
      - name: deploy Pages
        uses: actions/deploy-pages@v4